// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDBQWItmynliY5hDdBgmP2ssfSOKU6InA',
    appId: '1:357936102286:web:1479d2a3c23f6cda6f02df',
    messagingSenderId: '357936102286',
    projectId: 'mob3-uas-kel5',
    authDomain: 'mob3-uas-kel5.firebaseapp.com',
    storageBucket: 'mob3-uas-kel5.firebasestorage.app',
    measurementId: 'G-T6BK7NBXTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASUTTyNEe1Tkw3c6X8QIRRUWsgz_j3M9w',
    appId: '1:357936102286:android:59bba071c85d31d96f02df',
    messagingSenderId: '357936102286',
    projectId: 'mob3-uas-kel5',
    storageBucket: 'mob3-uas-kel5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-DkMIWS4YlmxbxDeOGqZ1j9-aa2UpLsY',
    appId: '1:357936102286:ios:fa20e71b51ff2fe16f02df',
    messagingSenderId: '357936102286',
    projectId: 'mob3-uas-kel5',
    storageBucket: 'mob3-uas-kel5.firebasestorage.app',
    iosBundleId: 'com.example.pinjamuang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-DkMIWS4YlmxbxDeOGqZ1j9-aa2UpLsY',
    appId: '1:357936102286:ios:fa20e71b51ff2fe16f02df',
    messagingSenderId: '357936102286',
    projectId: 'mob3-uas-kel5',
    storageBucket: 'mob3-uas-kel5.firebasestorage.app',
    iosBundleId: 'com.example.pinjamuang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDBQWItmynliY5hDdBgmP2ssfSOKU6InA',
    appId: '1:357936102286:web:6332396d5cd507116f02df',
    messagingSenderId: '357936102286',
    projectId: 'mob3-uas-kel5',
    authDomain: 'mob3-uas-kel5.firebaseapp.com',
    storageBucket: 'mob3-uas-kel5.firebasestorage.app',
    measurementId: 'G-9GP142QJLR',
  );
}
